theme: jekyll-theme-leap-day

# Site Info
title:              "My Blog"
description:        "Resume and Notes"
author_name:        "Simon NingXiao Ren" 

# Site Settings
url:                https://simonnxren.github.io # main url
#baseurl:            /about.html
permalink:          /:title # Post permalink
